[package]
name = "uc-xcompose"
description = "XCompose file parser and writer, with libxkbcommon's semantics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uc-keysym.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
